function outputPath = export_simulink_rls_golden(outputPath, stopTime)
%EXPORT_SIMULINK_RLS_GOLDEN Export the unmodified R2024b model RLS trace.
% The source .slx is only simulated.  This function never saves or edits it.

arguments
    outputPath (1, 1) string
    stopTime (1, 1) double {mustBePositive} = 0.02
end

assert(version('-release') == "2024b", ...
    "This golden trace must be generated by MATLAB R2024b.");

modelDir = "C:\Users\30276\Documents\Matlab Drive\MFPCC_work";
modelName = "MFPCC_DDM_coldstart_ESOrls";
originalDir = string(pwd);
cleanup = onCleanup(@() cd(originalDir));
cd(modelDir);

in = Simulink.SimulationInput(modelName);
in = in.setModelParameter("StopTime", compose("%.12g", stopTime));
out = sim(in);

id = out.get("id_log");
iq = out.get("iq_log");
ud = out.get("ud_log");
uq = out.get("uq_log");
thetaD = out.get("theta_d_log");
thetaQ = out.get("theta_q_log");
idHat = out.get("idhat_log");
iqHat = out.get("iqhat_log");

t = id.Time(:);
idData = id.Data(:);
iqData = iq.Data(:);
udData = ud.Data(:);
uqData = uq.Data(:);
thetaDData = orientTheta(thetaD.Data, numel(t));
thetaQData = orientTheta(thetaQ.Data, numel(t));

assert(isequal(iq.Time(:), t) && isequal(ud.Time(:), t) && ...
    isequal(uq.Time(:), t) && isequal(thetaD.Time(:), t) && ...
    isequal(thetaQ.Time(:), t) && isequal(idHat.Time(:), t) && ...
    isequal(iqHat.Time(:), t), ...
    "Logged RLS signals do not share a sample clock.");

data = [t, idData, iqData, udData, uqData, idHat.Data(:), iqHat.Data(:), ...
    thetaDData, thetaQData];
names = ["time_s", "id_a", "iq_a", "ud_v", "uq_v", ...
    "id_hat_a", "iq_hat_a", ...
    "theta_d_1", "theta_d_2", "theta_d_3", "theta_d_4", ...
    "theta_d_5", "theta_d_6", "theta_d_7", ...
    "theta_q_1", "theta_q_2", "theta_q_3", "theta_q_4", ...
    "theta_q_5", "theta_q_6", "theta_q_7"];
writetable(array2table(data, "VariableNames", names), outputPath);
fprintf("Exported %d unmodified-model samples to %s\n", size(data, 1), outputPath);
end

function value = orientTheta(value, sampleCount)
value = squeeze(value);
if size(value, 1) == 7 && size(value, 2) == sampleCount
    value = value.';
end
assert(isequal(size(value), [sampleCount, 7]), ...
    "Unexpected theta log shape [%s].", num2str(size(value)));
end
